(require 'powerline-evil)

;; (defun powerline-default-theme ()
;;   "Setup the default mode-line."
;;   (interactive)
;;   (setq-default mode-line-format
;;                 '("%e"
;;                   (:eval
;;                    (let* ((active (powerline-selected-window-active))
;;                           (mode-line (if active 'mode-line 'mode-line-inactive))
;;                           (face1 (if active 'powerline-active1 'powerline-inactive1))
;;                           (face2 (if active 'powerline-active2 'powerline-inactive2))
;;                           (separator-left (intern (format "powerline-%s-%s"
;; 							  (powerline-current-separator)
;;                                                           (car powerline-default-separator-dir))))
;;                           (separator-right (intern (format "powerline-%s-%s"
;;                                                            (powerline-current-separator)
;;                                                            (cdr powerline-default-separator-dir))))
;;                           (lhs (list (powerline-raw "%*" nil 'l)
;;                                      (when powerline-display-buffer-size
;;                                        (powerline-buffer-size nil 'l))
;;                                      (when powerline-display-mule-info
;;                                        (powerline-raw mode-line-mule-info nil 'l))
;;                                      (powerline-buffer-id nil 'l)
;;                                      (when (and (boundp 'which-func-mode) which-func-mode)
;;                                        (powerline-raw which-func-format nil 'l))
;;                                      (powerline-raw " ")
;;                                      (funcall separator-left mode-line face1)
;;                                      (when (boundp 'erc-modified-channels-object)
;;                                        (powerline-raw erc-modified-channels-object face1 'l))
;;                                      (powerline-major-mode face1 'l)
;;                                      (powerline-process face1)
;;                                      (powerline-minor-modes face1 'l)
;;                                      (powerline-narrow face1 'l)
;;                                      (powerline-raw " " face1)
;;                                      (funcall separator-left face1 face2)
;;                                      (powerline-vc face2 'r)
;;                                      (when (bound-and-true-p nyan-mode)
;;                                        (powerline-raw (list (nyan-create)) face2 'l))))
;;                           (rhs (list (powerline-raw global-mode-string face2 'r)
;;                                      (funcall separator-right face2 face1)
;; 				     (unless window-system
;; 				       (powerline-raw (char-to-string #xe0a1) face1 'l))
;; 				     (powerline-raw "%4l" face1 'l)
;; 				     (powerline-raw ":" face1 'l)
;; 				     (powerline-raw "%3c" face1 'r)
;; 				     (funcall separator-right face1 mode-line)
;; 				     (powerline-raw " ")
;; 				     (powerline-raw "%6p" nil 'r)
;;                                      (when powerline-display-hud
;;                                        (powerline-hud face2 face1)))))
;; 		     (concat (powerline-render lhs)
;; 			     (powerline-fill face2 (powerline-width rhs))
;; 			     (powerline-render rhs)))))))

;; (defun powerline-evil-vim-color-theme ()
;;   "Powerline's Vim-like mode-line with evil state at the beginning in color."
;;   (interactive)
;;   (setq-default mode-line-format
;;                 '("%e"
;;                   (:eval
;;                    (let* ((active (powerline-selected-window-active))
;;                           (mode-line (if active 'mode-line 'mode-line-inactive))
;;                           (face1 (if active 'powerline-active1 'powerline-inactive1))
;;                           (face2 (if active 'powerline-active2 'powerline-inactive2))
;;                           (separator-left (intern (format "powerline-%s-%s"
;;                                                           powerline-default-separator
;;                                                           (car powerline-default-separator-dir))))
;;                           (separator-right (intern (format "powerline-%s-%s"
;;                                                            powerline-default-separator
;;                                                            (cdr powerline-default-separator-dir))))
;;                           (lhs (list (let ((evil-face (powerline-evil-face)))
;;                                        (if evil-mode
;;                                            (powerline-raw (powerline-evil-tag) evil-face)))
;;                                      (powerline-buffer-id `(mode-line-buffer-id ,mode-line) 'l)
;;                                      (powerline-raw "[" mode-line 'l)
;;                                      (powerline-major-mode mode-line)
;;                                      (powerline-process mode-line)
;;                                      (powerline-raw "]" mode-line)
;;                                      (when (buffer-modified-p)
;;                                        (powerline-raw "[+]" mode-line))
;;                                      (when buffer-read-only
;;                                        (powerline-raw "[RO]" mode-line))
;;                                      (powerline-raw "[%z]" mode-line)
;;                                      ;; (powerline-raw (concat "[" (mode-line-eol-desc) "]") mode-line)
;;                                      (when (and (boundp 'which-func-mode) which-func-mode)
;;                                        (powerline-raw which-func-format nil 'l))
;;                                      (when (boundp 'erc-modified-channels-object)
;;                                        (powerline-raw erc-modified-channels-object face1 'l))
;;                                      (powerline-raw "[" mode-line 'l)
;;                                      (powerline-minor-modes mode-line)
;;                                      (powerline-raw "%n" mode-line)
;;                                      (powerline-raw "]" mode-line)
;;                                      (when (and vc-mode buffer-file-name)
;;                                        (let ((backend (vc-backend buffer-file-name)))
;;                                          (when backend
;;                                            (concat (powerline-raw "[" mode-line 'l)
;;                                                    (powerline-raw (format "%s / %s" backend (vc-working-revision buffer-file-name backend)))
;;                                                    (powerline-raw "]" mode-line)))))))
;;                           (rhs (list (powerline-raw '(10 "%i"))
;;                                      (powerline-raw global-mode-string mode-line 'r)
;;                                      (powerline-raw "%l," mode-line 'l)
;;                                      (powerline-raw (format-mode-line '(10 "%c")))
;;                                      (powerline-raw (replace-regexp-in-string  "%" "%%" (format-mode-line '(-3 "%p"))) mode-line 'r))))
;;                      (concat (powerline-render lhs)
;;                              (powerline-fill mode-line (powerline-width rhs))
;;                              (powerline-render rhs)))))))

;; My personal powerline theme. Default theme with just a mode status
(defun powerline-my-color-theme ()
  "Setup my mode-line."
  (interactive)
  (setq-default mode-line-format
                '("%e"
                  (:eval
                   (let* ((active (powerline-selected-window-active))
                          (mode-line (if active 'mode-line 'mode-line-inactive))
                          (face1 (if active 'powerline-active1 'powerline-inactive1))
                          (face2 (if active 'powerline-active2 'powerline-inactive2))
                          (separator-left (intern (format "powerline-%s-%s"
							  (powerline-current-separator)
                                                          (car powerline-default-separator-dir))))
                          (separator-right (intern (format "powerline-%s-%s"
                                                           (powerline-current-separator)
                                                           (cdr powerline-default-separator-dir))))
                          (lhs (list (let ((evil-face (powerline-evil-face)))
                                            (if evil-mode
                                              (powerline-raw (powerline-evil-tag) evil-face)))
                                     (powerline-raw "%*" nil 'l)
                                     (when powerline-display-buffer-size
                                       (powerline-buffer-size nil 'l))
                                     (when powerline-display-mule-info
                                       (powerline-raw mode-line-mule-info nil 'l))
                                     (powerline-buffer-id nil 'l)
                                     (when (and (boundp 'which-func-mode) which-func-mode)
                                       (powerline-raw which-func-format nil 'l))
                                     (powerline-raw " ")
                                     (funcall separator-left mode-line face1)
                                     (when (boundp 'erc-modified-channels-object)
                                       (powerline-raw erc-modified-channels-object face1 'l))
                                     (powerline-major-mode face1 'l)
                                     (powerline-process face1)
                                     (powerline-minor-modes face1 'l)
                                     (powerline-narrow face1 'l)
                                     (powerline-raw " " face1)
                                     (funcall separator-left face1 face2)
                                     (powerline-vc face2 'r)
                                     (when (bound-and-true-p nyan-mode)
                                       (powerline-raw (list (nyan-create)) face2 'l))))
                          (rhs (list (powerline-raw global-mode-string face2 'r)
                                     (funcall separator-right face2 face1)
				     (unless window-system
				       (powerline-raw (char-to-string #xe0a1) face1 'l))
				     (powerline-raw "%4l" face1 'l)
				     (powerline-raw ":" face1 'l)
				     (powerline-raw "%3c" face1 'r)
				     (funcall separator-right face1 mode-line)
				     (powerline-raw " ")
				     (powerline-raw "%6p" nil 'r)
                                     (when powerline-display-hud
                                       (powerline-hud face2 face1)))))
		     (concat (powerline-render lhs)
			     (powerline-fill face2 (powerline-width rhs))
			     (powerline-render rhs)))))))

;; My personal powerline theme. Default theme with just a mode status
(defun powerline-my-theme ()
  "Setup my mode-line."
  (interactive)
  (setq-default mode-line-format
                '("%e"
                  (:eval
                   (let* ((active (powerline-selected-window-active))
                          (mode-line (if active 'mode-line 'mode-line-inactive))
                          (face1 (if active 'powerline-active1 'powerline-inactive1))
                          (face2 (if active 'powerline-active2 'powerline-inactive2))
                          (separator-left (intern (format "powerline-%s-%s"
							  (powerline-current-separator)
                                                          (car powerline-default-separator-dir))))
                          (separator-right (intern (format "powerline-%s-%s"
                                                           (powerline-current-separator)
                                                           (cdr powerline-default-separator-dir))))
                          (lhs (list (if evil-mode
                                       (powerline-raw (powerline-evil-tag) mode-line))
                                     (powerline-raw "%*" nil 'l)
                                     (when powerline-display-buffer-size
                                       (powerline-buffer-size nil 'l))
                                     (when powerline-display-mule-info
                                       (powerline-raw mode-line-mule-info nil 'l))
                                     (powerline-buffer-id nil 'l)
                                     (when (and (boundp 'which-func-mode) which-func-mode)
                                       (powerline-raw which-func-format nil 'l))
                                     (powerline-raw " ")
                                     (funcall separator-left mode-line face1)
                                     (when (boundp 'erc-modified-channels-object)
                                       (powerline-raw erc-modified-channels-object face1 'l))
                                     (powerline-major-mode face1 'l)
                                     (powerline-process face1)
                                     (powerline-minor-modes face1 'l)
                                     (powerline-narrow face1 'l)
                                     (powerline-raw " " face1)
                                     (funcall separator-left face1 face2)
                                     (powerline-vc face2 'r)
                                     (when (bound-and-true-p nyan-mode)
                                       (powerline-raw (list (nyan-create)) face2 'l))))
                          (rhs (list (powerline-raw global-mode-string face2 'r)
                                     (funcall separator-right face2 face1)
				     (unless window-system
				       (powerline-raw (char-to-string #xe0a1) face1 'l))
				     (powerline-raw "%4l" face1 'l)
				     (powerline-raw ":" face1 'l)
				     (powerline-raw "%3c" face1 'r)
				     (funcall separator-right face1 mode-line)
				     (powerline-raw " ")
				     (powerline-raw "%6p" nil 'r)
                                     (when powerline-display-hud
                                       (powerline-hud face2 face1)))))
		     (concat (powerline-render lhs)
			     (powerline-fill face2 (powerline-width rhs))
			     (powerline-render rhs)))))))

(defun powerline-moe-theme ()
    "Powerline theme powered by moe-theme.el, WITH EVIL
It's recommended use this with `moe-light' or `moe-dark', but it's ok without them,
as long as setq `moe-theme-mode-line-color' first."
    (interactive)
    (cond ((eq (frame-parameter nil 'background-mode) 'light)
           (set-face-attribute 'mode-line-buffer-id nil :background nil :foreground "#1c1c1c")
             (set-face-attribute 'mode-line-inactive nil :background "#b2b2b2" :foreground "#ffffff")
             (set-face-attribute 'powerline-active2 nil :background "#585858" :foreground "#ffffff")
             (set-face-attribute 'powerline-inactive1 nil :background "#c6c6c6" :foreground "#585858")
             (set-face-attribute 'powerline-inactive2 nil :background "#e4e4e4" :foreground "#585858")
             (cond ((eq moe-theme-mode-line-color 'blue)
                    (set-face-attribute 'mode-line nil :background "#5fafd7" :foreground "#ffffff")
                    (set-face-attribute 'powerline-active1 nil :background "#afd7ff" :foreground "#005faf"))
                   ((eq moe-theme-mode-line-color 'green)
                    (set-face-attribute 'mode-line nil :background "#a1db00" :foreground "#005f00")
                    (set-face-attribute 'powerline-active1 nil :background "#d7ff87" :foreground "#008700"))
                   ((eq moe-theme-mode-line-color 'orange)
                    (set-face-attribute 'mode-line nil :background "#ff8700" :foreground "#ffffff")
                    (set-face-attribute 'powerline-active1 nil :background "#ffd787" :foreground "#d75f00"))
                   ((eq moe-theme-mode-line-color 'magenta)
                    (set-face-attribute 'mode-line nil :background "#ff4ea3" :foreground "#ffffff")
                    (set-face-attribute 'powerline-active1 nil :background "#ffafff" :foreground "#ff1f8b"))
                   ((eq moe-theme-mode-line-color 'yellow)
                    (set-face-attribute 'mode-line nil :background "#fce94f" :foreground "#875f00")
                    (set-face-attribute 'powerline-active1 nil :background "#ffff87" :foreground "#875f00"))
                   ((eq moe-theme-mode-line-color 'purple)
                    (set-face-attribute 'mode-line nil :background "#af5fd7" :foreground "#ffffff")
                    (set-face-attribute 'powerline-active1 nil :background "#e6a8df" :foreground "#6c0099"))
                   ((eq moe-theme-mode-line-color 'red)
                    (set-face-attribute 'mode-line nil :background "#ff4b4b" :foreground "#ffffff")
                    (set-face-attribute 'powerline-active1 nil :background "#ffafaf" :foreground "#cc0000"))
                   ((eq moe-theme-mode-line-color 'cyan)
                    (set-face-attribute 'mode-line nil :background "#5faf87" :foreground "#ffffff")
                    (set-face-attribute 'powerline-active1 nil :background "#87d7af" :foreground "#005f5f"))
                   ((eq moe-theme-mode-line-color 'w/b)
                    (set-face-attribute 'mode-line nil :background "#1c1c1c" :foreground "#ffffff")
                    (set-face-attribute 'powerline-active1 nil :background "#bcbcbc" :foreground "#3a3a3a")
                    (set-face-attribute 'mode-line-buffer-id nil :background nil :foreground "#ffffff"))))
          ((eq (frame-parameter nil 'background-mode) 'dark)
           (set-face-attribute 'mode-line-buffer-id nil :background nil :foreground "#080808")
           (set-face-attribute 'mode-line-inactive nil :background "#4e4e4e" :foreground "#9e9e9e")
           (set-face-attribute 'powerline-active2 nil :background "#ffffff" :foreground "#3a3a3a")
           (set-face-attribute 'powerline-inactive1 nil :background "#626262" :foreground "#eeeeee")
           (set-face-attribute 'powerline-inactive2 nil :background "#767676" :foreground "#e4e4e4")
           (cond ((eq moe-theme-mode-line-color 'blue)
                  (set-face-attribute 'mode-line nil :background "#5fafd7" :foreground "#ffffff")
                  (set-face-attribute 'powerline-active1 nil :background "#afd7ff" :foreground "#005faf"))
                 ((eq moe-theme-mode-line-color 'green)
                  (set-face-attribute 'mode-line nil :background "#a1db00" :foreground "#005f00")
                  (set-face-attribute 'powerline-active1 nil :background "#d7ff87" :foreground "#008700"))
                 ((eq moe-theme-mode-line-color 'orange)
                  (set-face-attribute 'mode-line nil :background "#ff8700" :foreground "#ffffff")
                  (set-face-attribute 'powerline-active1 nil :background "#ffd787" :foreground "#d75f00"))
                 ((eq moe-theme-mode-line-color 'magenta)
                  (set-face-attribute 'mode-line nil :background "#ff4ea3" :foreground "#ffffff")
                  (set-face-attribute 'powerline-active1 nil :background "#ffafff" :foreground "#ff1f8b"))
                 ((eq moe-theme-mode-line-color 'yellow)
                  (set-face-attribute 'mode-line nil :background "#fce94f" :foreground "#875f00")
                  (set-face-attribute 'powerline-active1 nil :background "#ffff87" :foreground "#875f00"))
                 ((eq moe-theme-mode-line-color 'purple)
                  (set-face-attribute 'mode-line nil :background "#af5fd7" :foreground "#ffffff")
                  (set-face-attribute 'powerline-active1 nil :background "#e6a8df" :foreground "#6c0099"))
                 ((eq moe-theme-mode-line-color 'red)
                  (set-face-attribute 'mode-line nil :background "#ff4b4b" :foreground "#ffffff")
                  (set-face-attribute 'powerline-active1 nil :background "#ffafaf" :foreground "#cc0000"))
                 ((eq moe-theme-mode-line-color 'cyan)
                  (set-face-attribute 'mode-line nil :background "#5faf87" :foreground "#ffffff")
                  (set-face-attribute 'powerline-active1 nil :background "#87d7af" :foreground "#005f5f"))
                 ((eq moe-theme-mode-line-color 'w/b)
                  (set-face-attribute 'mode-line nil :background "#ffffff" :foreground "#080808")
                  (set-face-attribute 'powerline-active1 nil :background "#bcbcbc" :foreground "#3a3a3a")
                  (set-face-attribute 'mode-line-buffer-id nil :background nil :foreground "#3a3a3a")))))
    (powerline-my-theme) ; The only change in this function from the original
    (powerline-reset)
    (setq moe-theme-powerline-enable-p t))

(provide 'powerline-evil-moe)
